---
title: "coffee rust"
author: Vitoria Betim
date: 21-05-2025
format: 
  html:
    toc: true
warning: false
message: false
editor: visual
---

## APRESENTAÇÃO

O conjunto de dados será o da ferrugem do café na Etiópia que está no arquivo de dados da nuvem.

## Importando os dados

Usaremos a função `gsheet2tbl()` do pacote $$gsheet$$ para carregar os dados no ambiente:

```{r}
library(gsheet)
cr<-gsheet2tbl("https://docs.google.com/spreadsheets/d/1bq2N19DcZdtax2fQW9OHSGMR0X2__Z9T/edit?gid=1871397229#gid=1871397229")
cr


```

## Visualizando os dados

Usaremos a função `datatable()` do pacote $$DT$$

```{r}
library(DT)

datatable(cr)
```

## Gráficos

Vamos aprender como fazer e editar um mapa no R.

```{r}
library(tidyverse)
library(ggthemes)
library(ggspatial)
cr|>
  ggplot(aes(lon, lat)) + geom_point()

library(rnaturalearth)
library(rnaturalearthhires)


remotes::install_github("ropensci/rnaturalearthhires")

ETH<-ne_states(country = "Ethiopia", returnclass = "sf")
ETH
cr
ETH|>
  ggplot()+geom_sf(fill = "white") + geom_point(data=cr,aes(lon,lat, color=inc)) + scale_color_viridis_c()+ theme_minimal() + annotation_scale(location = "tl") + annotation_north_arrow(location = "br", which_north= "true")+ labs(title= "Ferrugem do Café na Etiópia", x="Longitude", y="Latitude", subtitle= "Levantamento em fazendas", caption= "Fonte: Betim et al. (2025)", Color = "Incidência(%)")

ggsave("mapa_ethiopia.png", bg = "white", width = 10)
```

# Fazendo
